#
# This is free software, lisence use MIT.
# 
# Copyright (C) 2019 P3TERX <https://p3terx.com>
# Copyright (C) 2020 KFERMercer <KFER.Mercer@gmail.com>
# 
# <https://github.com/KFERMercer/OpenWrt-CI>
#

name: OpenWrt-CI

on:
  push:
    branches: 
      - master
  # schedule:
  #   - cron: 0 20 * * *
  release:
    types: [published]

jobs:

  build_openwrt:

    name: Build OpenWrt firmware

    runs-on: ubuntu-latest

    if: github.event.repository.owner.id == github.event.sender.id

    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Space cleanup
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          docker rmi `docker images -q`
          sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
          sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php* android*
          sudo -E apt-get update
          sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3 unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs gcc-multilib g++-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler antlr3 gperf swig libtinfo5
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean
          # sudo mkdir -p -m 777 /mnt/openwrt/bin /mnt/openwrt/build_dir/host /mnt/openwrt/build_dir/hostpkg /mnt/openwrt/dl /mnt/openwrt/feeds /mnt/openwrt/staging_dir
          # ln -s /mnt/openwrt/bin ./bin
          # mkdir -p ./build_dir
          # ln -s -f /mnt/openwrt/build_dir/host ./build_dir/host
          # ln -s -f /mnt/openwrt/build_dir/hostpkg ./build_dir/hostpkg
          # ln -s /mnt/openwrt/dl ./dl
          # ln -s /mnt/openwrt/feeds ./feeds
          # ln -s /mnt/openwrt/staging_dir ./staging_dir
          df -h
      - name: Update feeds
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a
      - name: Generate configuration file
        run: |
          rm -f ./.config*
          touch ./.config
          #
          # 在 cat >> .config <<EOF 到 EOF 之间粘贴你的编译配置, 需注意缩进关系
          # 例如:
          cat >> .config <<EOF
          CONFIG_TARGET_x86=y
          CONFIG_TARGET_x86_64=y
          CONFIG_TARGET_x86_64_DEVICE_generic=y
          CONFIG_GNUTLS_ALPN=y
          CONFIG_GNUTLS_ANON=y
          CONFIG_GNUTLS_DTLS_SRTP=y
          CONFIG_GNUTLS_HEARTBEAT=y
          CONFIG_GNUTLS_OCSP=y
          CONFIG_GNUTLS_PSK=y
          CONFIG_OCSERV_HTTP_PARSER=y
          CONFIG_OCSERV_PROTOBUF=y
          CONFIG_PACKAGE_certtool=y
          CONFIG_PACKAGE_libgnutls=y
          CONFIG_PACKAGE_libnettle=y
          CONFIG_PACKAGE_libprotobuf-c=y
          # CONFIG_PACKAGE_luci-app-accesscontrol is not set
          # CONFIG_PACKAGE_luci-app-adbyby-plus is not set
          # CONFIG_PACKAGE_luci-app-ddns is not set
          # CONFIG_PACKAGE_luci-app-ipsec-vpnd is not set
          CONFIG_PACKAGE_luci-app-ocserv=y
          # CONFIG_PACKAGE_luci-app-rclone_INCLUDE_fuse-utils is not set
          # CONFIG_PACKAGE_luci-app-rclone_INCLUDE_rclone-ng is not set
          # CONFIG_PACKAGE_luci-app-rclone_INCLUDE_rclone-webui is not set
          # CONFIG_PACKAGE_luci-app-unblockmusic is not set
          # CONFIG_PACKAGE_luci-app-upnp is not set
          # CONFIG_PACKAGE_luci-app-uugamebooster is not set
          # CONFIG_PACKAGE_luci-app-vsftpd is not set
          # CONFIG_PACKAGE_luci-app-wol is not set
          # CONFIG_PACKAGE_luci-app-xlnetacc is not set
          # CONFIG_PACKAGE_luci-app-zerotier is not set
          CONFIG_PACKAGE_luci-theme-argon=y
          CONFIG_PACKAGE_luci-theme-material=y
          CONFIG_PACKAGE_luci-theme-netgear=y
          CONFIG_PACKAGE_ocserv=y
          # CONFIG_TARGET_ROOTFS_SQUASHFS is not set
          CONFIG_TARGET_ROOTFS_TARGZ=y
          # CONFIG_UnblockNeteaseMusic_Go is not set
          # CONFIG_UnblockNeteaseMusic_NodeJS is not set
          CONFIG_PACKAGE_UnblockNeteaseMusic=y
          CONFIG_PACKAGE_UnblockNeteaseMusicGo=y
          CONFIG_PACKAGE_adbyby=y
          CONFIG_PACKAGE_etherwake=y
          CONFIG_PACKAGE_grub2=y
          CONFIG_PACKAGE_grub2-efi=y
          CONFIG_PACKAGE_iptables-mod-ipsec=y
          CONFIG_PACKAGE_kmod-crypto-acompress=y
          CONFIG_PACKAGE_kmod-crypto-cbc=y
          CONFIG_PACKAGE_kmod-crypto-deflate=y
          CONFIG_PACKAGE_kmod-crypto-des=y
          CONFIG_PACKAGE_kmod-crypto-echainiv=y
          CONFIG_PACKAGE_kmod-crypto-hmac=y
          CONFIG_PACKAGE_kmod-crypto-md5=y
          # CONFIG_PACKAGE_kmod-ip-vti is not set
          # CONFIG_PACKAGE_kmod-ip6-vti is not set
          CONFIG_PACKAGE_kmod-ipsec=y
          CONFIG_PACKAGE_kmod-ipsec4=y
          CONFIG_PACKAGE_kmod-ipsec6=y
          CONFIG_PACKAGE_kmod-ipt-ipsec=y
          CONFIG_PACKAGE_kmod-iptunnel4=y
          CONFIG_PACKAGE_kmod-iptunnel6=y
          CONFIG_PACKAGE_kmod-lib-zlib-deflate=y
          CONFIG_PACKAGE_kmod-lib-zlib-inflate=y
          # CONFIG_PACKAGE_kmod-xfrm-interface is not set
          CONFIG_PACKAGE_libminiupnpc=y
          CONFIG_PACKAGE_libnatpmp=y
          CONFIG_PACKAGE_miniupnpd=y
          CONFIG_PACKAGE_strongswan=y
          CONFIG_PACKAGE_strongswan-charon=y
          # CONFIG_PACKAGE_strongswan-charon-cmd is not set
          # CONFIG_PACKAGE_strongswan-default is not set
          CONFIG_PACKAGE_strongswan-ipsec=y
          # CONFIG_PACKAGE_strongswan-isakmp is not set
          # CONFIG_PACKAGE_strongswan-libtls is not set
          CONFIG_PACKAGE_strongswan-minimal=y
          # CONFIG_PACKAGE_strongswan-mod-addrblock is not set
          CONFIG_PACKAGE_strongswan-mod-aes=y
          # CONFIG_PACKAGE_strongswan-mod-af-alg is not set
          # CONFIG_PACKAGE_strongswan-mod-agent is not set
          # CONFIG_PACKAGE_strongswan-mod-attr is not set
          # CONFIG_PACKAGE_strongswan-mod-attr-sql is not set
          # CONFIG_PACKAGE_strongswan-mod-blowfish is not set
          # CONFIG_PACKAGE_strongswan-mod-ccm is not set
          # CONFIG_PACKAGE_strongswan-mod-cmac is not set
          # CONFIG_PACKAGE_strongswan-mod-connmark is not set
          # CONFIG_PACKAGE_strongswan-mod-constraints is not set
          # CONFIG_PACKAGE_strongswan-mod-coupling is not set
          # CONFIG_PACKAGE_strongswan-mod-ctr is not set
          # CONFIG_PACKAGE_strongswan-mod-curl is not set
          # CONFIG_PACKAGE_strongswan-mod-curve25519 is not set
          # CONFIG_PACKAGE_strongswan-mod-des is not set
          # CONFIG_PACKAGE_strongswan-mod-dhcp is not set
          # CONFIG_PACKAGE_strongswan-mod-dnskey is not set
          # CONFIG_PACKAGE_strongswan-mod-duplicheck is not set
          # CONFIG_PACKAGE_strongswan-mod-eap-identity is not set
          # CONFIG_PACKAGE_strongswan-mod-eap-md5 is not set
          # CONFIG_PACKAGE_strongswan-mod-eap-mschapv2 is not set
          # CONFIG_PACKAGE_strongswan-mod-eap-radius is not set
          # CONFIG_PACKAGE_strongswan-mod-eap-tls is not set
          # CONFIG_PACKAGE_strongswan-mod-farp is not set
          # CONFIG_PACKAGE_strongswan-mod-fips-prf is not set
          # CONFIG_PACKAGE_strongswan-mod-forecast is not set
          # CONFIG_PACKAGE_strongswan-mod-gcm is not set
          # CONFIG_PACKAGE_strongswan-mod-gcrypt is not set
          CONFIG_PACKAGE_strongswan-mod-gmp=y
          # CONFIG_PACKAGE_strongswan-mod-gmpdh is not set
          # CONFIG_PACKAGE_strongswan-mod-ha is not set
          CONFIG_PACKAGE_strongswan-mod-hmac=y
          # CONFIG_PACKAGE_strongswan-mod-kernel-libipsec is not set
          CONFIG_PACKAGE_strongswan-mod-kernel-netlink=y
          # CONFIG_PACKAGE_strongswan-mod-ldap is not set
          # CONFIG_PACKAGE_strongswan-mod-led is not set
          # CONFIG_PACKAGE_strongswan-mod-load-tester is not set
          # CONFIG_PACKAGE_strongswan-mod-md4 is not set
          # CONFIG_PACKAGE_strongswan-mod-md5 is not set
          # CONFIG_PACKAGE_strongswan-mod-mysql is not set
          CONFIG_PACKAGE_strongswan-mod-nonce=y
          # CONFIG_PACKAGE_strongswan-mod-openssl is not set
          # CONFIG_PACKAGE_strongswan-mod-pem is not set
          # CONFIG_PACKAGE_strongswan-mod-pgp is not set
          # CONFIG_PACKAGE_strongswan-mod-pkcs1 is not set
          # CONFIG_PACKAGE_strongswan-mod-pkcs11 is not set
          # CONFIG_PACKAGE_strongswan-mod-pkcs12 is not set
          # CONFIG_PACKAGE_strongswan-mod-pkcs7 is not set
          # CONFIG_PACKAGE_strongswan-mod-pkcs8 is not set
          CONFIG_PACKAGE_strongswan-mod-pubkey=y
          CONFIG_PACKAGE_strongswan-mod-random=y
          # CONFIG_PACKAGE_strongswan-mod-rc2 is not set
          # CONFIG_PACKAGE_strongswan-mod-resolve is not set
          # CONFIG_PACKAGE_strongswan-mod-revocation is not set
          CONFIG_PACKAGE_strongswan-mod-sha1=y
          # CONFIG_PACKAGE_strongswan-mod-sha2 is not set
          # CONFIG_PACKAGE_strongswan-mod-smp is not set
          CONFIG_PACKAGE_strongswan-mod-socket-default=y
          # CONFIG_PACKAGE_strongswan-mod-socket-dynamic is not set
          # CONFIG_PACKAGE_strongswan-mod-sql is not set
          # CONFIG_PACKAGE_strongswan-mod-sqlite is not set
          # CONFIG_PACKAGE_strongswan-mod-sshkey is not set
          CONFIG_PACKAGE_strongswan-mod-stroke=y
          # CONFIG_PACKAGE_strongswan-mod-test-vectors is not set
          # CONFIG_PACKAGE_strongswan-mod-uci is not set
          # CONFIG_PACKAGE_strongswan-mod-unity is not set
          CONFIG_PACKAGE_strongswan-mod-updown=y
          # CONFIG_PACKAGE_strongswan-mod-vici is not set
          # CONFIG_PACKAGE_strongswan-mod-whitelist is not set
          CONFIG_PACKAGE_strongswan-mod-x509=y
          # CONFIG_PACKAGE_strongswan-mod-xauth-eap is not set
          CONFIG_PACKAGE_strongswan-mod-xauth-generic=y
          CONFIG_PACKAGE_strongswan-mod-xcbc=y
          # CONFIG_PACKAGE_strongswan-pki is not set
          # CONFIG_PACKAGE_strongswan-scepclient is not set
          # CONFIG_PACKAGE_strongswan-swanctl is not set
          CONFIG_PACKAGE_uugamebooster=y
          CONFIG_PACKAGE_vsftpd-alt=y
          CONFIG_PACKAGE_wol=y
          # CONFIG_PACKAGE_xfrm is not set
          CONFIG_PACKAGE_zerotier=y
          CONFIG_STRONGSWAN_ROUTING_TABLE="220"
          CONFIG_STRONGSWAN_ROUTING_TABLE_PRIO="220"
          CONFIG_VSFTPD_USE_UCI_SCRIPTS=y
          # CONFIG_ZEROTIER_ENABLE_DEBUG is not set
          # CONFIG_ZEROTIER_ENABLE_SELFTEST is not set
          EOF
          #
          # ===============================================================
          # 
          sed -i 's/^[ \t]*//g' ./.config
          make defconfig
      - name: Make download
        run: |
          make download -j8 || make download -j1 V=s
          rm -rf $(find ./dl/ -size -1024c)
          df -h
      - name: Compile firmware
        run: |
          make -j$(nproc) || make -j1 V=s
          echo "======================="
          echo "Space usage:"
          echo "======================="
          df -h
          echo "======================="
          du -h ./ --max-depth=1
          du -h /mnt/openwrt/ --max-depth=1 || true
      - name: Prepare artifact
        run: |
          mkdir -p ./artifact/firmware
          mkdir -p ./artifact/package
          mkdir -p ./artifact/buildinfo
          rm -rf $(find ./bin/targets/ -type d -name "packages")
          cp -rf $(find ./bin/targets/ -type f) ./artifact/firmware/
          cp -rf $(find ./bin/packages/ -type f -name "*.ipk") ./artifact/package/
          cp -rf $(find ./bin/targets/ -type f -name "*.buildinfo" -o -name "*.manifest") ./artifact/buildinfo/
      - name: Deliver buildinfo
        uses: actions/upload-artifact@v2
        with:
          name: OpenWrt_buildinfo
          path: ./artifact/buildinfo/

      - name: Deliver package
        uses: actions/upload-artifact@v2
        with:
          name: OpenWrt_package
          path: ./artifact/package/

      - name: Deliver firmware
        uses: actions/upload-artifact@v2
        with:
          name: OpenWrt_firmware
          path: ./bin/targets/

      - name: Upload release asset
        if: github.event == 'release'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.YOURTOKEN }}
          file: ./artifact/firmware/*
          tag: ${{ github.ref }}
          file_glob: true
